// Placeholder glazes until the site reads from the database.
// "color" is the main glaze color, "accent" is where it breaks or pools.
const MOCK_GLAZES = [
  { name: "Coyote Cobalt Blue", code: "MBG008", brand: "Coyote", colorFamily: "blue", color: "#1d2257", accent: "#7e86c4",
    firingRange: "Midfire, Cone 5-6", application: "Brush On", finish: "Glossy", opacity: "Opaque",
    foodSafe: "Yes, AP non-toxic", fluidity: "Stable, does not run", tags: ["Smooth", "Blue", "Coyote", "Cobalt"], favorites: 28, added: "2026-09-28" },
  { name: "Shino Gold", code: "MBG045", brand: "Coyote", colorFamily: "orange", color: "#c9853f", accent: "#f0d3a2",
    firingRange: "Midfire, Cone 5-6", application: "Brush On", finish: "Satin", opacity: "Opaque",
    foodSafe: "Yes, AP non-toxic", fluidity: "Stable, does not run", tags: ["Shino", "Warm"], favorites: 41, added: "2026-08-14" },
  { name: "Blue Rutile", code: "PC-20", brand: "Amaco", colorFamily: "blue", color: "#3b5a78", accent: "#c9b892",
    firingRange: "Midfire, Cone 5-6", application: "Brush On", finish: "Glossy", opacity: "Opaque",
    foodSafe: "Yes, dinnerware safe", fluidity: "Fluid, may run", tags: ["Variegated", "Speckled", "Blue"], favorites: 63, added: "2026-07-02" },
  { name: "Seaweed", code: "PC-25", brand: "Amaco", colorFamily: "green", color: "#3c5a3a", accent: "#a7b46f",
    firingRange: "Midfire, Cone 5-6", application: "Brush On", finish: "Glossy", opacity: "Translucent",
    foodSafe: "Yes, dinnerware safe", fluidity: "Fluid, may run", tags: ["Green", "Breaking"], favorites: 37, added: "2026-09-05" },
  { name: "Sapphire", code: "SW-123", brand: "Mayco", colorFamily: "blue", color: "#22346e", accent: "#6a5d9e",
    firingRange: "Midfire, Cone 6", application: "Brush On", finish: "Glossy", opacity: "Semi-transparent",
    foodSafe: "Yes, dinnerware safe", fluidity: "Stable, does not run", tags: ["Blue", "Mirror"], favorites: 22, added: "2026-09-19" },
  { name: "Alabaster Satin", code: "MBG074", brand: "Coyote", colorFamily: "white", color: "#ece6d8", accent: "#c8bea6",
    firingRange: "Midfire, Cone 5-6", application: "Dip", finish: "Satin", opacity: "Opaque",
    foodSafe: "Yes, AP non-toxic", fluidity: "Stable, does not run", tags: ["White", "Smooth"], favorites: 19, added: "2026-06-21" },
  { name: "Firebrick Red", code: "SW-158", brand: "Mayco", colorFamily: "red", color: "#8f2a20", accent: "#d06a3a",
    firingRange: "Midfire, Cone 6", application: "Brush On", finish: "Glossy", opacity: "Opaque",
    foodSafe: "Yes, dinnerware safe", fluidity: "Stable, does not run", tags: ["Red", "Warm"], favorites: 30, added: "2026-08-30" },
  { name: "Honey Flux", code: "PC-1", brand: "Amaco", colorFamily: "yellow", color: "#c49a2c", accent: "#f2d66b",
    firingRange: "Midfire, Cone 5-6", application: "Brush On", finish: "Glossy", opacity: "Translucent",
    foodSafe: "Yes, dinnerware safe", fluidity: "Very fluid", tags: ["Yellow", "Runny"], favorites: 12, added: "2026-05-11" },
  { name: "Lavender Mist", code: "MBG118", brand: "Coyote", colorFamily: "purple", color: "#8c7aa8", accent: "#d4c7e3",
    firingRange: "Midfire, Cone 5-6", application: "Brush On", finish: "Matte", opacity: "Opaque",
    foodSafe: "Yes, AP non-toxic", fluidity: "Stable, does not run", tags: ["Purple", "Soft"], favorites: 17, added: "2026-09-25" },
  { name: "Speckled Oatmeal", code: "SW-401", brand: "Mayco", colorFamily: "beige", color: "#d9c7a3", accent: "#8a6b45", speckled: true,
    firingRange: "Midfire, Cone 6", application: "Dip", finish: "Matte", opacity: "Opaque",
    foodSafe: "Yes, dinnerware safe", fluidity: "Stable, does not run", tags: ["Speckled", "Neutral"], favorites: 52, added: "2026-09-30" },
  { name: "Turquoise Matt", code: "MBG027", brand: "Coyote", colorFamily: "teal", color: "#3b9b9a", accent: "#9fd4c9",
    firingRange: "Midfire, Cone 5-6", application: "Brush On", finish: "Matte", opacity: "Opaque",
    foodSafe: "Yes, AP non-toxic", fluidity: "Stable, does not run", tags: ["Teal", "Textured"], favorites: 33, added: "2026-07-17" },
  { name: "Obsidian", code: "SW-102", brand: "Mayco", colorFamily: "black", color: "#141414", accent: "#4a4038",
    firingRange: "Midfire, Cone 6", application: "Brush On", finish: "Glossy", opacity: "Opaque",
    foodSafe: "Yes, dinnerware safe", fluidity: "Stable, does not run", tags: ["Black", "Smooth"], favorites: 26, added: "2026-04-03" },
  { name: "Rose Quartz", code: "MBG132", brand: "Coyote", colorFamily: "pink", color: "#d9a3a6", accent: "#f3d7d2",
    firingRange: "Midfire, Cone 5-6", application: "Brush On", finish: "Satin", opacity: "Translucent",
    foodSafe: "Yes, AP non-toxic", fluidity: "Stable, does not run", tags: ["Pink", "Soft"], favorites: 44, added: "2026-09-12" },
  { name: "Iron Lustre", code: "PC-23", brand: "Amaco", colorFamily: "brown", color: "#4e3020", accent: "#b07a42",
    firingRange: "Midfire, Cone 5-6", application: "Brush On", finish: "Glossy", opacity: "Opaque",
    foodSafe: "Yes, dinnerware safe", fluidity: "Fluid, may run", tags: ["Brown", "Breaking"], favorites: 21, added: "2026-06-08" },
  { name: "Galaxy Speckle", code: "SW-506", brand: "Mayco", colorFamily: "multi", color: "#33264f", accent: "#d97d55", speckled: true,
    firingRange: "Midfire, Cone 6", application: "Brush On", finish: "Glossy", opacity: "Opaque",
    foodSafe: "Yes, dinnerware safe", fluidity: "Stable, does not run", tags: ["Speckled", "Multicolor"], favorites: 15, added: "2026-10-01" },
  { name: "Ash Grey", code: "MBG071", brand: "Coyote", colorFamily: "grey", color: "#8f8c86", accent: "#c9c5bc",
    firingRange: "Midfire, Cone 5-6", application: "Dip", finish: "Matte", opacity: "Opaque",
    foodSafe: "Yes, AP non-toxic", fluidity: "Stable, does not run", tags: ["Grey", "Textured"], favorites: 9, added: "2026-03-22" },
  { name: "Tangerine", code: "LG-61", brand: "Amaco", colorFamily: "orange", color: "#e2732e", accent: "#f6b267",
    firingRange: "Lowfire, Cone 05", application: "Brush On", finish: "Glossy", opacity: "Opaque",
    foodSafe: "Yes, dinnerware safe", fluidity: "Stable, does not run", tags: ["Orange", "Bright"], favorites: 11, added: "2026-08-02" },
  { name: "Celadon", code: "C-21", brand: "Amaco", colorFamily: "green", color: "#9dbba0", accent: "#d6e3cf",
    firingRange: "Midfire, Cone 4-6", application: "Dip", finish: "Glossy", opacity: "Transparent",
    foodSafe: "Yes, dinnerware safe", fluidity: "Stable, does not run", tags: ["Green", "Celadon", "Smooth"], favorites: 48, added: "2026-09-08" },
  { name: "Butter Yellow", code: "SC-75", brand: "Mayco", colorFamily: "yellow", color: "#efd77e", accent: "#fbecb4",
    firingRange: "Lowfire, Cone 06", application: "Brush On", finish: "Glossy", opacity: "Opaque",
    foodSafe: "Yes, dinnerware safe", fluidity: "Stable, does not run", tags: ["Yellow", "Smooth"], favorites: 7, added: "2026-02-15" },
  { name: "Plum Crawl", code: "MBG066", brand: "Coyote", colorFamily: "purple", color: "#5a2c4c", accent: "#c9a6b8",
    firingRange: "Midfire, Cone 5-6", application: "Brush On", finish: "Matte", opacity: "Opaque",
    foodSafe: "No, decorative only", fluidity: "Stable, does not run", tags: ["Purple", "Textured", "Crawl"], favorites: 24, added: "2026-07-29" },
  { name: "Chun Plum", code: "PC-58", brand: "Amaco", colorFamily: "red", color: "#6e2033", accent: "#9fb0d6",
    firingRange: "Midfire, Cone 5-6", application: "Brush On", finish: "Glossy", opacity: "Opaque",
    foodSafe: "Yes, dinnerware safe", fluidity: "Fluid, may run", tags: ["Red", "Variegated"], favorites: 35, added: "2026-09-02" },
];
