-- Westridge Ceramics, second setup file. Run once in Supabase
-- (Dashboard → SQL Editor → New query → paste → Run). Safe to run again.
--
-- 1. Extra dropdown choices people add (e.g. a "Satin" finish).
--
-- The built-in choices (Brush On, Dip, Low Fire, Glossy, ...) live in the site's code;
-- this table only holds the ones added from the upload form. They show up in the
-- upload dropdowns and in the filter menu for everyone.

create table if not exists public.glaze_options (
  id         bigint generated by default as identity primary key,
  category   text not null check (category in ('application', 'firing', 'finish', 'opacity', 'foodSafe')),
  label      text not null check (char_length(label) between 1 and 40),
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now()
);

-- One "Satin" per category, however it's capitalized
create unique index if not exists glaze_options_unique on public.glaze_options (category, lower(label));

alter table public.glaze_options enable row level security;

drop policy if exists "glaze options: anyone can read" on public.glaze_options;
create policy "glaze options: anyone can read" on public.glaze_options
  for select using (true);

drop policy if exists "glaze options: logged in can add" on public.glaze_options;
create policy "glaze options: logged in can add" on public.glaze_options
  for insert to authenticated with check (created_by = auth.uid());

-- 2. Any logged-in person can edit or delete any glaze. (The site also asks for the
--    studio password first.) This replaces the earlier rule that only the person who
--    added a glaze could change it.
drop policy if exists "glaze library: edit samples or your own" on public.glazes;
drop policy if exists "glaze library: delete samples or your own" on public.glazes;

drop policy if exists "glaze library: logged in can edit" on public.glazes;
create policy "glaze library: logged in can edit" on public.glazes
  for update to authenticated using (true) with check (true);

drop policy if exists "glaze library: logged in can delete" on public.glazes;
create policy "glaze library: logged in can delete" on public.glazes
  for delete to authenticated using (true);

-- Undo after a delete puts the glaze back with its original owner
drop policy if exists "glaze library: logged in can add" on public.glazes;
create policy "glaze library: logged in can add" on public.glazes
  for insert to authenticated with check (true);
